name: Go-CI Release

on:
  create:
    tags:
      - '*'

jobs:
  release:
    name: Realease with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: helloci
    strategy:
      matrix:
        go_version: [ 1.18 ]
        os: [ ubuntu-22.04 ]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Validates GO releaser config
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: check

      - name: Create release on GitHub
        # uses: docker://goreleaser/goreleaser:latest
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          pwd
          ls -laph
          go build  -v -o goci .

      - name: Publish to Registry (Aliyun)
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: registry.cn-shenzhen.aliyuncs.com/jeffid/goci  # docker image 的名字
          username: ${{ secrets.DOCKER_USERNAME}} # 用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 密码
          registry: registry.cn-shenzhen.aliyuncs.com # Registry
          dockerfile: Dockerfile # 指定 Dockerfile 的位置
          tag_names: true # 是否将 release 的 tag 作为 docker image 的 tag

      - name: Publish to Registry (Tencnet Cloud)
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ccr.ccs.tencentyun.com/jeffid/goci  # docker image 的名字
          username: ${{ secrets.TC_DOCKER_USERNAME}} # 用户名
          password: ${{ secrets.TC_DOCKER_PASSWORD }} # 密码
          registry: ccr.ccs.tencentyun.com # Registry
          dockerfile: Dockerfile # 指定 Dockerfile 的位置
          tag_names: true # 是否将 release 的 tag 作为 docker image 的 tag


